name: Thermal Limitation of Seagrasses in Great Barrier Reef Ecosystem
channels:
    - conda-forge
dependencies:
    - python=3.7    # Python version 3.7
    - cartopy       # Geographic plotting toolkit
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - xarray        # N-d labeled array library
    - cmocean       # Colormap setup for standardizing commonly-plotting oceanographic variables
    - os            # Methods for interacting with the operating system

